### ISSUE TITLE
socket not found

### ISSUE THREAD

**Issue by tharrmeehan** [nwg-piotr/nwg-dock-hyprland#30]
**Describe the bug**
Hello, this is just to let you know that there were some breaking changes in the hyprland-git repo since 
https://github.com/hyprwm/Hyprland/pull/5788

Not sure if you want to update yet.

**To Reproduce**
1. Updating to latest git

**Screenshots**
![grafik](https://github.com/nwg-piotr/nwg-dock-hyprland/assets/58373200/2d7630ed-4454-475d-b616-a2a50ffcd28a)

**Desktop (please complete the following information):**
 - endeavour os, latest arch kernel
 - go version : go-2:1.22.2-1
 - gtk-layer-shell version: gtk-layer-shell-0.8.2-1

**Comment by nwg-piotr** [comment]
Yes, I already updated nwg-panel and nwg-displays. The dock needs to wait for it's turn, maybe tonight. Thanks for reporting anyway.

**Comment by nwg-piotr** [comment]
What's currently on the `hyprdir` branch, should probably work. I can't test, since the hyprland-git package stopped building tonight.

**Comment by aidan-gibson** [comment]
hyprdir branch initially worked, then I pinned something and it segfaulted. 
```
nwg-dock-hyprland
INFO[0000] Using auto-detected launcher command: 'nwg-drawer'
INFO[0000] Using style: /home/bruh/.config/nwg-dock-hyprland/style.css
ERRO[0000] Unable to show grid button: open /home/bruh/.cache/nwg-dock-pinned: no such file or directory
ERRO[0003] Unable to show grid button: open /home/bruh/.cache/nwg-dock-pinned: no such file or directory
ERRO[0008] Unable to show grid button: open /home/bruh/.cache/nwg-dock-pinned: no such file or directory
ERRO[0016] Unable to show grid button: open /home/bruh/.cache/nwg-dock-pinned: no such file or directory
ERRO[0016] Unable to show grid button: open /home/bruh/.cache/nwg-dock-pinned: no such file or directory
ERRO[0022] Unable to show grid button: open /home/bruh/.cache/nwg-dock-pinned: no such file or directory
INFO[0024] pin thorium-browser
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e3243]

goroutine 1 [running]:
main.buildMainBox(0xc000292078)
	/home/bruh/nwg-dock-hyprland/main.go:218 +0xb83
main.main.func5.1()
	/home/bruh/nwg-dock-hyprland/main.go:556 +0x17
reflect.Value.call({0x636620?, 0xc000290190?, 0xc00002f900?}, {0x6e602f, 0x4}, {0x0, 0x0, 0x3?})
	/usr/lib/go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0x636620?, 0xc000290190?, 0xc00029e0c0?}, {0x0?, 0x3?, 0xc000012a20?})
	/usr/lib/go/src/reflect/value.go:380 +0xb9
github.com/gotk3/gotk3/glib.sourceFunc(0x0?)
	/home/bruh/go/pkg/mod/github.com/gotk3/gotk3@v0.6.3/glib/glib.go:324 +0xa5
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:17495 +0x3f
github.com/gotk3/gotk3/gtk.Main(...)
	/home/bruh/go/pkg/mod/github.com/gotk3/gotk3@v0.6.3/gtk/gtk.go:1242
main.main()
	/home/bruh/nwg-dock-hyprland/main.go:657 +0x172b
```
Subsequent attempts to start it also segfault.
```
nwg-dock-hyprland
INFO[0000] Using auto-detected launcher command: 'nwg-drawer'
INFO[0000] Using style: /home/bruh/.config/nwg-dock-hyprland/style.css
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e3243]

goroutine 1 [running]:
main.buildMainBox(0xc0000740c0)
	/home/bruh/nwg-dock-hyprland/main.go:218 +0xb83
main.main()
	/home/bruh/nwg-dock-hyprland/main.go:567 +0x145e
```

Arch 6.8.8-zen1-1-zen

**Comment by nwg-piotr** [comment]
Can't confirm. Even if I remove the `nwg-dock-pinned` file, it gets re-created. Could you check whether the `/home/bruh/.cache/nwg-dock-pinned` even exists?

**Comment by tharrmeehan** [comment]
Hi, sorry for the late response, didn't have my computer with me. Everything works as expected on the latest git.
