### ISSUE TITLE
Panic on start when -c is passed

### ISSUE THREAD

**Issue by caferen** [nwg-piotr/nwg-dock-hyprland#42]
**Describe the bug**
The dock started to crash on start yesterday when I specify `-c`.

**To Reproduce**
1- Start the dock: `nwg-dock-hyprland -c "rofi -show drun -theme config.rasi"`
2- Immediately crashes with

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5ee243]

goroutine 1 [running]:
main.buildMainBox(0xc0000ac070)
        nwg-dock-hyprland/main.go:218 +0xb83
main.main()
        nwg-dock-hyprland/main.go:567 +0x145e
```

**Expected behavior**
Dock starts

**Desktop (please complete the following information):**
 - Linux distribution: Arch Linux, the dock is installed via nix: v0.1.8
 - go version: go1.22.3 linux/amd64
 - gtk-layer-shell version: 0.8.2-1

**Comment by caferen** [comment]
I'm closing this issue as after a day of consistently crashing, the issue went away on it's own.
